---
- include: pre_requisite.yml
  when: not osd_containerized_deployment

- include: ./scenarios/journal_collocation.yml
  when:
    - journal_collocation
    - not osd_containerized_deployment

- include: ./scenarios/raw_multi_journal.yml
  when:
    - raw_multi_journal
    - not osd_containerized_deployment

- include: ./scenarios/osd_directory.yml
  when:
    - osd_directory
    - not osd_containerized_deployment

- include: ./scenarios/bluestore.yml
  when:
    - osd_objectstore == 'bluestore'
    - not osd_containerized_deployment

- include: ./docker/main.yml
  when: osd_containerized_deployment
