- name: open port 4000 for swarm manager
  ufw: rule=allow port=4000 proto=tcp
- name: Launching swarm managers
  tags: swarm
  docker:
    name: manager
    image: swarm
    command: "manage --tlsverify --tlscacert=/certs/ca.pem --tlscert=/certs/cert.pem --tlskey=/certs/key.pem -H :4000 --replication --advertise {{ansible_host}}:4000 consul://{{consul0_ip}}:8500"
    state: reloaded
    count: 1
    ports:
      - 4000:4000
    expose:
      - 4000
    volumes:
      - /home/{{ansible_user}}/.certs:/certs
- name: Copy reverse ssh service file
  template: src=reverse-ssh.service.j2 dest=/etc/systemd/system/reverse-ssh.service
- name: (Re)start reverse ssh service
  service: name=reverse-ssh state=restarted
- name: enable reverse ssh service at boot
  service: name=reverse-ssh enabled=yes