- debug: "msg={{ manager0_ip }}"
- name: swarm manager container
  docker:
    name: manager
    image: swarm
    docker_url: ":4000"
    command: "--replication advertise {{manager0_ip}}:4000 
      consul://{{consul0_ip}}:8500"