# https://docs.docker.com/engine/installation/linux/debian/#debian-jessie-80-64-bit
- name: Bash profile (root)
  copy: src=.bash_profile dest=/root
- name: "Bash profile {{ansible_user}}"
  copy: "src=.bash_profile dest=/home/{{ansible_user}}"

# - copy: "src=sources.list dest=/etc/apt/"

- name: Updating Apt repository
  apt: update_cache=yes
# - name: Updating distribution
#   apt: upgrade=dist
  
- name: Installing packages
  apt: name={{ item }} state=latest
  with_items:
    - apt-transport-https
    - ca-certificates
- name: Installing python
  apt: name=python state=latest

# - name: Setting IP to Static with settings for UW
#   template: src=interfaces.j2 dest=/etc/network/interfaces
#   notify:
#     - restart networking

# - name: Setup firewall
- apt: name=ufw state=latest
- ufw: "rule=limit port={{ansible_port}} proto=tcp"
- ufw: state=enabled

- name: Make directory for certs
  file: "path={{cert_dir}} state=directory"
- name: Transfer CA cert
  copy:
    src: "{{ca_filepath}}/ca.pem"
    dest: "{{cert_dir}}/"
- name: Transfer node's public cert
  copy: 
    src: "{{ca_filepath}}/{{inventory_hostname}}/{{inventory_hostname}}-cert.pem"
    dest: "{{cert_dir}}/cert.pem"
- name: Transfer node's private key
  copy: 
    src: "{{ca_filepath}}/{{inventory_hostname}}/{{inventory_hostname}}-priv-key.pem"
    dest: "{{cert_dir}}/key.pem"
