# https://docs.docker.com/engine/installation/linux/debian/#debian-jessie-80-64-bit
- copy: src=.bash_profile dest=/root
- copy: "src=.bash_profile dest=/home/{{ansible_user}}"

- name: Updating Apt repository
  apt: update_cache=yes
- name: Updating distribution
  apt: upgrade=dist
  
- name: Installing packages
  apt: name={{ item }} state=latest
  with_items:
    - apt-transport-https
    - ca-certificates
- name: Installing python
  apt: name=python state=latest

- name: Setting IP to Static with settings for UW
  template: src=interfaces.j2 dest=/etc/network/interfaces
  notify:
    - restart networking

- apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
- file: path=/etc/apt/sources.list.d/ state=directory
- name: Copying docker list for Debian Jessie
  copy: src=docker.list dest=/etc/apt/sources.list.d/docker.list

- name: Install Docker
  apt: name=docker-engine state=latest

- block:
  - name: Install docker-py
    pip: name=docker-py state=latest
  rescue:
    - debug: msg='Caught error with pip'
    - name: Downloading pip
      get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/tmp
    - name: Installing pip
      command: python /tmp/get-pip.py
    - name: Install docker-py (again)
      pip: name=docker-py state=latest

# - name: Setup firewall
- apt: name=ufw state=latest
- ufw: rule=limit port=2424 proto=tcp
- ufw: state=enabled

- name: Make directory for certs
  file: "path={{cert_dir}} state=directory"
- name: Transfer CA cert
  copy:
    src: "{{ca_filepath}}/ca.pem"
    dest: "{{cert_dir}}/"
- name: Transfer node's public cert
  copy: 
    src: "{{ca_filepath}}/{{inventory_hostname}}/{{inventory_hostname}}-cert.pem"
    dest: "{{cert_dir}}/cert.pem"
- name: Transfer node's private key
  copy: 
    src: "{{ca_filepath}}/{{inventory_hostname}}/{{inventory_hostname}}-priv-key.pem"
    dest: "{{cert_dir}}/key.pem"
