- ufw: rule=allow port=8500 proto=tcp
- name: consul container
  docker:
    name: consul
    image: progrium/consul
    command: "-server -bootstrap"
    state: started
    count: 1
    ports:
      - 8500:8500
