- apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
- file: path=/etc/apt/sources.list.d/ state=directory
- name: Copying docker list for Debian Stretch
  copy: src=docker.list dest=/etc/apt/sources.list.d/docker.list
- name: update apt-get
  apt: update_cache=yes
- name: Install Docker
  apt: name=docker-engine state=latest

- block:
  - name: Install docker-py
    pip: name=docker-py state=latest
  rescue:
    - debug: msg='Caught error with pip'
    - name: Downloading pip
      get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/tmp
    - name: Installing pip
      command: python /tmp/get-pip.py
    - name: Install docker-py (again)
      pip: name=docker-py state=latest

- name: start Docker
  service: name=docker state=started
- name: enable Docker on boot
  service: name=docker enabled=yes
