---
- hosts: mons
  tasks:
    - ufw: rule=allow port=6789 proto=tcp

- hosts: osds
  tasks:
    - ufw:
        rule: allow
        port: 6800:7300
        # from_ip: "{{item}}"
        from_ip: "{{hostvars[item].ansible_host}}"
        proto: tcp
        delete: yes 
      # with_items: "{{ansible_all_ipv4_addresses}}"
      with_items: "{{groups['all']}}"