---
- hosts: docker
  tags: docker
  
  tasks:
    # TODO git pull, docker-compose for eye candy
    - name: Starting Trigger
      docker:
        name: Trigger
        image: tbenst/trigger
        state: started
        count: 1
        ports:
          - 5000:5000

