---
- include: migrations.yml
# TODO
# - include: certificate-authority.yml
- include: common.yml
# - include: soft-reset.yml
- include: consuls.yml
- include: managers.yml
- include: workers.yml
- include: ceph.yml