---
# - include: load-facts.yml

- hosts: all
  tasks:
    # - debug: msg="Hello World"
    - shell: sudo apt-get clean
    - shell: cd /var/lib/apt
    - shell: sudo mv lists lists.old
    - shell: sudo mkdir -p lists/partial
    - shell: sudo apt-get clean
    - shell: sudo apt-get update
