---
- include: load-facts.yml

- hosts: all
  tasks:
    - debug: msg="Running Migrations"
    - apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D state=absent
