---
- hosts: all
  
  tasks:
    - debug: "msg=System {{ inventory_hostname }} has ip {{ ansible_host }}"

- hosts: certificate-authority
  tasks:
    - name: removing certificates
      file: "path={{ca_dir}} state=absent"
