---
- hosts: docker
  tags: docker
  
  tasks:
    - name: Stopping all Docker images
      shell: "docker stop $(docker ps -a -q)"
      ignore_errors: yes
    - name: Removing all Docker images
      shell: "docker rm $(docker ps -a -q)"
      ignore_errors: yes
