---
- hosts: all
  
  tasks:
    - debug: msg="System {{ inventory_hostname }} has ip {{ ansible_host }}"
    - debug: msg="now on {{hostvars[item]['ansible_enp0s7']['ipv4']['address']}}"
      with_items: groups['all']