- ufw: rule=allow port=2376 proto=tcp
- name: Create docker.service.d directory
  file: path=/etc/systemd/system/docker.service.d state=directory
- name: Adding Docker daemon options
  template: src=docker.conf.j2 dest=/etc/systemd/system/docker.service.d/docker.conf
  notify:
    - Stop Docker
    - Reload Systemd
    - Start Docker
# - name: Restart Docker tcp socket
#   service: name=docker-tcp.socket state=restarted
# http://tech.paulcz.net/2016/01/secure-docker-with-tls/

- name: Join swarm
  tags: drone
  docker:
    name: swarm
    image: swarm
    command: "join --advertise={{ ansible_host }}:2376 consul://{{consul0_ip}}:8500"
    state: started
    # state: reloaded
    count: 1
    # use_tls: verify
    # tls_ca_cert: "{{cert_dir}}/ca.pem"
    # tls_client_cert: "{{cert_dir}}/cert.pem"
    # tls_client_key: "{{cert_dir}}/key.pem"